### ISSUE TITLE
LookupDefinition fails on subweb with LookupWebUrl = "~site" value

### ISSUE THREAD

**Issue by sergeisnitko** [SubPointSolutions/spmeta2#1013]
# Tokens in LookupWebUrl

**SPMeta2 CSOM Standard 1.2.120**

LookupWebUrl can use tokens in LookupFieldDefinition (like ~site and ~sitecollection).
The behavior of ~sitecollection is clear. It gets the url of the root web of the site collection where we provision the model

~site is not clear. For the first time, I thought that it is the token of the web where I deploy a lookup field (in structure of webs). But during debugging I understood that it takes the url of the site of the current ClientContext. It is not a good idea, because I'm not sure on what web in my model the Lookup field have to be provisioned and one lookup definition could be used on several webs. So, if I use the token ~site, it means that the list for lookup have to be on the web that I used for my ClientContext of SharePoint. 

For example:
I have a structure of 100 webs and on each web in the deep we have a lot of lists and lookups on them. And I need to set the LookupWebUrl to set the Web of the list for the lookup.

I found the #863 issue and it is like mine. It is not a good option to make a different model for each subweb for me, because it would be very hard to maintain the model in future and hard to use the solution.

May be it is an option to make another token for this situation and to make the structured web url for LookupWebUrl

It is not a critical option, but can be a good one in future. 
Now I have a small workaround that updates LookupWebUrl in all LookupFieldDefinitions in my model

```c#
public static ModelNode UpdateLookupWebUrls(this ModelNode model, string WebPath)
{
    var IsWeb = model.Value.GetType() == typeof(WebDefinition);

    if (IsWeb)
    {
        var WebUrl = ((WebDefinition)model.Value).Url;
        if (WebUrl != "/")
        {
            WebPath += "/" + ((WebDefinition)model.Value).Url;
        }                
    }

    model.ChildModels.ToList().ForEach(InModel =>
    {
        if (InModel.Value.GetType() == typeof(LookupFieldDefinition))
        {
            ((LookupFieldDefinition)InModel.Value).LookupWebUrl += WebPath.Replace("//", "/");
        }
        InModel.UpdateLookupWebUrls(WebPath);
    });

    return model;
}
```

And I can use this function before deploy the model
```c#
    var xWebModel = ModelsInfo.xWebModel();
    xWebModel.UpdateLookupWebUrls("");

    xWebModel.SetIncrementalProvisionModelId("xWebModel");
    Ctx.DeployModel(xHubWebModel, Incremental);
```

This works fine for me in my situation.

**Comment by SubPointSupport** [comment]
Most likely, bug. 

~site token should refer to the current web in terms of provisioned model, not the current ClientContext. We'll double-check that.

**Comment by SubPointSupport** [comment]
Looking into this, going to add more tests this week.

**Comment by SubPointSupport** [comment]
@sergeisnitko, we believe that the whole token replacement functionality works well and the issue is limited to the lookup field only.

We had similar issue some time ago and make replacement service work only with Site or Web enforcing a particular reference to either Site or Web while calling it. However, it seems that with lookup field we still use ClientContext temporary allowing its usage:

https://github.com/SubPointSolutions/spmeta2/blob/dev/SPMeta2/SPMeta2.CSOM/ModelHandlers/Fields/LookupFieldModelHandler.cs#L164

Frankly saying, not sure why. Replacement service should always work with the "current" site or web depending on which node of the provisioned mode we are on. 

In this articular case, for the lookup field, we have to pass either site or web (depending where the lookup field is deployed to). We'll write some tests around this to ensure that no regression is introduced.

Meanwhile, would you please share a few models or at least a logic behind unexpected ~site values?

**Comment by SubPointSupport** [comment]
Confirming the issue for both CSOM/SSOM. Lookup field won't work if .LookupWebUrl refers to the current web site with token "~site". Fixing up.
