### ISSUE TITLE
.AddContentTypeLink() should work with content type ID

### ISSUE THREAD

**Issue by vladivanovrf** [SubPointSolutions/spmeta2#1016]
Hello

Test case: **SPMeta2 CSOM Foundation 1.2.120. SharePoint 2016 Eng.**

I found a bug with adding especially "Item" content type link to list. It looks like .AddContentTypeLink(BuiltInContentTypeId.Item) method don't do any staff.  There are no any exceptions, just content type link is not added after model provisioning. This problem is actual for diffrent list templates.

**SPMeta2 model**:
```
var webModel = SPMeta2Model.NewWebModel(currentWeb =>
            {
                currentWeb
                    .AddList(ListsInfo.Announcements(), currentList =>
                    {
                        currentList
                            .AddContentTypeLink(BuiltInContentTypeId.Item)
                            ;
                    })
                    ;
            });
```

```
public static ListDefinition Announcements()
{
            return new ListDefinition
            {
                Title = "Announcements",
                CustomUrl = "Lists/Announcements",
                ContentTypesEnabled = true,
                TemplateType = 104,
                DraftVersionVisibility = "0",
                EnableAttachments = false,
                TitleResource = new List<ValueForUICulture> {new ValueForUICulture { CultureId = 1033, Value = "Announcements" } }
            };
 }
```

**Comment by SubPointSupport** [comment]
Does ListsInfo.Announcements() have .ContentTypesEnabled property set to true?

**Comment by vladivanovrf** [comment]
Yes
```
public static ListDefinition Announcements()
        {
            return new ListDefinition
            {
                Title = "Announcements",
                CustomUrl = "Lists/Announcements",
                ContentTypesEnabled = true,
                TemplateType = 104,
                DraftVersionVisibility = "0",
                EnableAttachments = false,
                TitleResource = new List<ValueForUICulture> {new ValueForUICulture { CultureId = 1033, Value = "Announcements" } }
            };
        }
```

**Comment by SubPointSupport** [comment]
Content type operations within a list
http://docs.subpointsolutions.com/spmeta2/kb/kb-m2-000003.html

Add as a ContentTypeLinkDefinition setting up content type name. ID won't work, and BuiltInContentTypeId.Item.Name is set to "Item". That works in ENG locale but non-english installtations won't work. You should add your content type name in ContentTypeLinkDefinition obj,

**Comment by vladivanovrf** [comment]
I have english SharePoint with russian language pack, but current site collection and web have only english language. Ok, I've made another model with ContentTypeLinkDefinition,  set ContentTypeName = "Item", and ContentTypeId  = BuiltInContentTypeId.Item because it is required. This model doesn't add "Item" content type link to list and has no any exceptions aither:
```
var webModel = SPMeta2Model.NewWebModel(currentWeb =>
            {
                currentWeb
                    .AddList(ListsInfo.Announcements(), currentList =>
                    {
                        currentList
                            .AddContentTypeLink(new ContentTypeLinkDefinition {
                                ContentTypeId = BuiltInContentTypeId.Item,
                                ContentTypeName = "Item"
                            })
                            ;
                    })
                    ;
            });
```

**Comment by SubPointSupport** [comment]
Yep, should be fine.

Content type would be fetched by Name = "Item". Check if the current web has available content types with name "Item".

**Comment by vladivanovrf** [comment]
But last model, which I wrote, doesn't add content type link.
Sure, "Item" content type exists on site collection. I can remove it by name with SPMeta2 from another list on this web, for example:
```
.AddList(ListsInfo.Actions(), currentList =>
                    {
                        currentList
                            .AddRemoveContentTypeLinks(new RemoveContentTypeLinksDefinition
                            {
                                ContentTypes = new List<ContentTypeLinkValue>
                                {
                                    new ContentTypeLinkValue { ContentTypeName = "Item" }
                                }
                            })
                            ;
                    })
```

**Comment by SubPointSupport** [comment]
Rejecting due to lack of details. 

The issue has its own template with several areas to fill out - SharePoint API/SPMeta2 versions/SPMeta2 model which causes troubles. Either update this issue or create a new one providing suggested details.

Once done, we'll have a deeper look.

![image](https://cloud.githubusercontent.com/assets/8142869/25143721/d589f800-24ae-11e7-89a0-607de02a3fc0.png)

**Comment by vladivanovrf** [comment]
Oh sure, sorry. I've updated issue.

> Content type operations within a list
> http://docs.subpointsolutions.com/spmeta2/kb/kb-m2-000003.html
> 
> Add as a ContentTypeLinkDefinition setting up content type name. ID won't work

I saw such comments in your code (here https://github.com/SubPointSolutions/spmeta2/blob/master/SPMeta2/SPMeta2.CSOM/ModelHandlers/ContentTypeLinkModelHandler.cs):

```
// trying to find by content type id
// will never be resolved, actually
// list content types have different ID

//if (result == null && !string.IsNullOrEmpty(contentTypeLinkModel.ContentTypeId))
//    result = list.ContentTypes.GetById(contentTypeLinkModel.ContentTypeId);
```

What do you think about another method for getting list content type by ID? For example I usually use such method in CSOM (of course parent content type Id should be loaded before this):

```
result = list.ContentTypes.Cast<ContentType>().FirstOrDefault(
       ct => ct.Parent.StringId == contentTypeLinkModel.ContentTypeId);
```

For SSOM it wiil be in the same way

**Comment by vladivanovrf** [comment]
And I think I found a problem place in your code. 

Function "FindListContentType" in https://github.com/SubPointSolutions/spmeta2/blob/master/SPMeta2/SPMeta2.CSOM/ModelHandlers/ContentTypeLinkModelHandler.cs in most of cases return that "Item" content type have already existed in the list, because many content types ids start with "0x01". My method from the post above will exclude this situation. Using "StartsWith" on content type id in searching parent content type is very bad idea.

**Comment by SubPointSupport** [comment]
Ouch, indeed, absolutely outstanding catch, @vladivanovrf. Really big thanks for bringing that up.

FindListContentType() method, as well as other functions to find a content type, tries to find a content type by Name. Failing to find by name, it tries to find by content type id (that's a legacy behavior, we should not really rely on this!). And that's where the issue can occur. However, adding content types should only work using Name as ContentTypeId within a list would be different.

In your case, content type must be found by Name = "Item". If it can't be found, then a wrong content type name was used. That was an original idea. How, we clearly see that trying to resolve "Item" content type would pass FindListContentType() function further to the resolution by ID, and then return something by "sub-match" with StartsWith(). This is wrong (our bad!), seems to be a bug which can be seen only for out of the box content types. Meaning, it can't be replicated for custom content types at all - such content types have a custom ContentTypeId so they won't ever be found. That's why no one really found that before, and that's why it does not work for you and your model.

With some out of the box content types, such as Item, indeed, seems we need to modify FindListContentType() method to either match exact content type id value (which probably won't ever be a case for a list content type) or remove this bit of logic at all. The whole search by Id thing is really old and legacy, comes back to late 2012 - early 2013, just FYI. Sure, we admit that there are some bits here and there written really bad, that's true.

Now, here is how we can move forward:
* We'll write additional regression tests to add content type to a list
* Adding custom content types to lists / libraries
* Adding item content type to lists / libraries (such as your model)
* Fixing up CSOM/SSOM implementation (updating FindListContentType() and other methods)

Once tests green, we can be sure we didn't break anything plus covered your case. Hope that makes sense but feel free to add more content here.

**Comment by vladivanovrf** [comment]
> This is wrong (our bad!), seems to be a bug which can be seen only for out of the box content types. Meaning, it can't be replicated for custom content types at all - such content types have a custom ContentTypeId so they won't ever be found.

You are wrong. I can give you another example.
2 custom content types:
1. Id = 0x0100AAAAAAAA, ParentId = 0x01
2. Id = 0x0100AAAAAAAA00BBBBBBBB, ParentId = 0x0100AAAAAAAA
If content type number 2 exists in the list, content type numer 1 would never been added by SPMeta2 during your code.

You should use such code in FindListContentType() method for catching content type by id in CSOM:
```
result = list.ContentTypes.Cast<ContentType>().FirstOrDefault(
   ct => ct.Parent.StringId == contentTypeLinkModel.ContentTypeId);
```

And before that you should load parent content type id by such code in WithResolvingModelHost() method.

```
context.Load(list,
   l => l.ContentTypes.Include(
      ct => ct.Parent.StringId));
```

This code always returns the correct content type by id or null, if the content type is not exists in the list.

**Comment by SubPointSupport** [comment]
Yes, agree on everything said.

**Comment by SubPointSupport** [comment]
> What do you think about another method for getting list content type by ID? For example I usually use such method in CSOM (of course parent content type Id should be loaded before this):

```cs
result = list.ContentTypes.Cast<ContentType>().FirstOrDefault(
       ct => ct.Parent.StringId == contentTypeLinkModel.ContentTypeId);
```
>In the result will be our list content type or null if the list doesn't have such content type link.
For SSOM it wiil be in the same way

Oops... let us test this.

**Comment by SubPointSupport** [comment]
@vladivanovrf, this is very nice! Fixed both CSOM/SSOM, running more tests to ensure regression.

The following models pass:
```cs
var announcementList = ModelGeneratorService.GetRandomDefinition<ListDefinition>(def =>
            {
                def.TemplateType = BuiltInListTemplateTypeId.Announcements;
                def.ContentTypesEnabled = true;
            });

            var model = SPMeta2Model.NewWebModel(web =>
            {
                web.AddList(announcementList, list =>
                {
                    list.AddContentTypeLink(new ContentTypeLinkDefinition
                    {
                        ContentTypeId = BuiltInContentTypeId.Item,
                        ContentTypeName = "Item"
                    });
                });
            });

            TestModel(model);
```

Deployment to document library works as well:
```cs
var announcementList = ModelGeneratorService.GetRandomDefinition<ListDefinition>(def =>
            {
                def.TemplateType = BuiltInListTemplateTypeId.DocumentLibrary;
                def.ContentTypesEnabled = true;
            });

            var model = SPMeta2Model.NewWebModel(web =>
            {
                web.AddList(announcementList, list =>
                {
                    list.AddContentTypeLink(new ContentTypeLinkDefinition
                    {
                        ContentTypeId = BuiltInContentTypeId.Item,
                        ContentTypeName = "Item"
                    });
                });
            });

            TestModel(model);
```

**Comment by vladivanovrf** [comment]
Ok, very good :)

**Comment by SubPointSupport** [comment]
Looks good, closed this one.

We'll have to re-engineer other content type operations within a list such as a remove, hide and reorder.

**Comment by SubPointSupport** [comment]
@vladivanovrf, fixed for both CSOM/SSOM. Looks really great, many thanks for the hint. We are looking into related functionality and have to re-engineer the following areas:
* .RemoveContentTypeLink() should work with content type ID #1020
* .HideContentTypeLink() should work with content type ID #1021
* .AddUniqueContentTypeOrder() should work with content type ID #1022

For every case we are going to refactor and share codebase for content type lookup in the list plus add some tests. Quite a job so that we are expecting to have beta release next week or so.
