### ISSUE TITLE
Incorrect ~site/~sitecollection tokens resolve in NavigationNodes

### ISSUE THREAD

**Issue by digital88** [SubPointSolutions/spmeta2#1025]
When I provision below models on "/sites/test/" site collection (LCID = 1049, template STS#0), results are:
On root web:
* Top1 node = Top2 node = /sites/test/

On child web:
* ChildTop1 node = /sites/test/
* ChildTop2 node = /sites/test/Forum

When I create Host-named sitecollection "test.dev.mycompany.ru" (LCID = 1049, template STS#0) and provision same model, results are:
On root web:
* Top1 node = Top2 node = test.dev.mycompany.ru

On child web:
* ChildTop1 node = ChildTop2 node = test.dev.mycompany.ru/Forum

~sitecollection token resolved as ~site token for child web in host named site collection. They should resolve as in first example.

### SharePoint API
CSOM Sharepoint 2016 ENG + RUS lang pack, august 2016 CU

### SPMeta2 API
SPMeta2 1.2.110 CSOM

### SPMeta2 model
```cs
var model = SPMeta2Model.NewWebModel(web=>
{
  web.AddWeb(new WebDefinition()
  {
    Title = "Forum",
    LCID = 1049,
    Url = "Forum",
    WebTemplate = BuiltInWebTemplates.Collaboration.CommunitySite
  }, childWeb =>
  {
    childWeb.AddTopNavigationNode(new TopNavigationNodeDefinition()
    {
      Title = "ChildTop1",
      Url = "~sitecollection"
    });
    childWeb.AddTopNavigationNode(new TopNavigationNodeDefinition()
    {
      Title = "ChildTop2",
      Url = "~site"
    });
  });
});

var model2 = SPMeta2Model.NewWebModel(web=>
{
  web.AddTopNavigationNode(new TopNavigationNodeDefinition()
  {
    Title = "Top1",
    Url = "~sitecollection"
  });
  web.AddTopNavigationNode(new TopNavigationNodeDefinition()
  {
    Title = "Top2",
    Url = "~site"
  });
});
```

**Comment by SubPointSupport** [comment]
@digital88 correct, all makes sense. Double-checking tests and source code, it seems to be some kind of regression. In a nutshell, "~site" goes to the current web server related URL (on which an artifact gets provisioned) and "~sitecollection" renders as a current site collection server related URL.

Might be related to the following ones:
* Enhance Top/QuickLaunchNodeDefinition - add ~sitecollection/~site tokens support #448
* Incorrect ~site token resolution for CSOM for the subwebs #863
* LookupDefinition fails on subweb with LookupWebUrl = "~site" value #1013

**Comment by SubPointSupport** [comment]
@digital88 could you please check SPSite / SPWeb output for .ServerRelativeUrl property on your sites / webs?
* "/sites/test/"
* "/sites/test/forum"
* "/test.dev.mycompany.ru"
* "/test.dev.mycompany.ru/forum"

What does PowerShell return for these sites / webs?

**Comment by digital88** [comment]
In order:
/sites/test
/sites/test/Forum
/
/Forum

**Comment by SubPointSupport** [comment]
Right, thank you.  We had a look into regression tests. All looks good, can't see failures or obvious issues. 

A random guess is that "~sitecollection" isn't resolved to "/" but rather to an empty string "". 
"~site" is resolved to "/Forum". 

Now, having "/" or "" might push SharePoint to have a navigation link to the website itself. That's why the issue might be misleading, the "~sitecollection" token actually resolves into "/" or "" which on a subweb would literally mean itself, the subweb. "~site" would be resolved correctly into "/Forum" which would point a right subweb.

We aren't sure about that guess but checking as this behavior might be reproduced with the root website at a root site collection and a few websites plus raw tokens such as "~sitecollection".

Also, to move forward, you may check the values SPMeta2 gets for these tokens. Here is how:
* Enable verbose logging via .config file, configure default listeners under SPMeta2 source plus Verbose level, example can be found here: - https://github.com/SubPointSolutions/spmeta2/blob/master/SPMeta2/SPMeta2.Regression.Tests/SPMeta2.Regression.Tests.dll.config
* Alternatively, you might handle logging messaged with your own class as shown here - http://docs.subpointsolutions.com/spmeta2/extensibility/custom-logging.html

We log token replacements as following:
* TraceService.VerboseFormat((int)LogEventId.ModelProvisionCoreCall, "Original Url: [{0}]", urlValue);
* TraceService.VerboseFormat((int)LogEventId.ModelProvisionCoreCall, "Token replaced Url: [{0}]", newUrlValue);

That's what you can get from the logs.

Meanwhile, we are testing your scenarios on the root site collection. We'll let you know how it goes.

**Comment by SubPointSupport** [comment]
@digital88, reproduced. You don't need to do anything.

As mentioned, we resolve "~sitecollection" token into an empty string "" instead of "/".
On a "top level" site collection  "~sitecollection" for a subweb would return "" which would set a navigation node link to the subweb itself. We have to return "/" in that case. Non-rooted site collectoins such as /teams, /portal and so on gives the right result as well as office365. 

Our testing didn't catch this due to...
* All tests have "~sitecollection/something-random-here" or the same with "~site"
* All validation uses the same codebase to resolve tokens (so bug just asserts itself)

All major breaks were on either incorrect list / web resolve for lookup fields or incorrect URL resolve for the content editor web part content URL. All of these are quite limited scenarios which don't include this particular navigation thing with "raw" tokens - "~site" and "sitecollection" without anything.

Fixing up, really sorry for the inconvenience.

**Comment by digital88** [comment]
Great, thank you!

**Comment by digital88** [comment]
And one question: in first example, where Top1 node = Top2 node = /sites/test/ in the end top navigation contained only one node (last), because SPMeta looks navigation nodes by url, and if it finds one, replaces with new one if it has same url. But what if I want two node with different names but with one Url?

**Comment by SubPointSupport** [comment]
Try using "~sitecollection/" and "~site/", that might be a temporary fix.

Most likely, resolution into an empty string "" was meant for values such as "~sitecollection/my-url" to avoid double-slash in the very beginning. Working out the right fix for all cases but this might work for you allowing to move forward.

>And one question: in first example, where Top1 node = Top2 node = /sites/test/ in the end top navigation contained only one node (last), because SPMeta looks navigation nodes by url, and if it finds one, replaces with new one if it has same url. But what if I want two node with different names but with one Url?

Correct, won't work. URL is used as a key to find the right node. We either should use Title or Url, and unfortunately decided to go with Url enabling "renaming" scenarios rather than changing URL scenarios. We had to pick one. Moving forward, it can be considered adding additional property to indicate a lookup field - either Title or Url so that one would be immutable and the other one could be changed.  What's your view on this?

**Comment by digital88** [comment]
You may consider adding bool ShouldReplace property, then:
1) Try find node by Url if it exists;
2) If node does not exists, continue as usual;
3) If node exists, compare their Titles;
4) If Titles are equal, and ShouldReplace = true, replace node with new definition;
5) If Titles are equal, and ShouldReplace = false, add new node with new definition;
6) If Titles are not equal, add new node with new definition;

**Comment by SubPointSupport** [comment]
Yea, additional property is a must. That way we would be able to make a clear desition on how a navigation node should be found.
