### ISSUE TITLE
IsSharePointOnlineContext fails to Recognize Claim Based Authentication Context

### ISSUE THREAD

**Issue by adaoust** [SubPointSolutions/spmeta2#1036]
Hi @SubPointSupport,

Because we use claim cookies for authentication instead of the SharePointOnlineCredentials the IsSharePointOnlineContext utility fails to return true for SharePoint Online connections. I encountered this issue while debugging why Taxonomy operations were still failing after the latest fix and noticed that the TryRetryService.TryWithRetry is only called when IsSharePointOnlineContext returns true.

With that being said, in the past to identify which version the context is created for, I have use the ClientContext.ServerVersion > 16.1 or something similar.

Thanks,

Alex

**Comment by SubPointSupport** [comment]
This is pretty serious thing we broke.

IsSharePointOnlineContext was introduced with the recent taxonomy API related regression in O365. We haven't seen it happening on-prem, that's why tried to detect if it's SharePoint Online and then apply try-retry logic. Meant to be retried only for SharePoint Online.

Understand, we didn't cover all the cases sticking to type checking. First of all, we can check the server version of the context. 16.1 must indicate SharePoint Online (we hope SP2016 won't ever get this number). Next, we can expose IsSharePointOnlineContext as a replaceable service underneath so that you'll have an ability to replace the actual logic of detection with you own code. That would work in case of emergency.

What's your view on that? Would it be a better solution than the one existing?

**Comment by SubPointSupport** [comment]
This is pretty serious thing we broke.

IsSharePointOnlineContext was introduced with the recent taxonomy API related regression in O365. We haven't seen it happening on-prem, that's why tried to detect if it's SharePoint Online and then apply try-retry logic. Meant to be retried only for SharePoint Online.

Understand, we didn't cover all the cases sticking to type checking. First of all, we can check the server version of the context. 16.1 must indicate SharePoint Online (we hope SP2016 won't ever get this number). Next, we can expose IsSharePointOnlineContext as a replaceable service underneath so that you'll have an ability to replace the actual logic of detection with you own code. That would work in case of emergency.

What's your view on that? Would it be a better solution than the one existing?

**Comment by SubPointSupport** [comment]
Also, what's your timeline? Seems that the old version won't work due to taxonomy issue and the latest one would fail on the IsSharePointOnlineContext detection? So you guts stuck and that's a blocker, right?

**Comment by adaoust** [comment]
I personally use the ServerVersion to determine what version of CSOM I'm coding against so I think it's safe to use it for that check. Hopefully, like you said, SP2016 will never become 16.1 or maybe then it will have the new slow Taxonomy API anyway 😄 If you think exposing the service is a good idea, I wouldn't be against it. It adds more flexibility to SPMeta2 and that's always good.

In terms of timeline, it's not urgent, whenever I need to fix something urgently I just replace the model handler in the Provisioning Service with my own (usually just yours with a temporary fix).

Something like this:

```
var customTaxonomyTermModelHandler = new CustomTaxonomyTermModelHandler();
provisioningService.ModelHandlers.Remove(customTaxonomyTermModelHandler.TargetType);
provisioningService.RegisterModelHandler(customTaxonomyTermModelHandler);
```

Then when you guys fix the bugs I get rid of those custom handlers.

Thanks!

**Comment by SubPointSupport** [comment]
Sweet, we'll work it out. Indeed, we tend to expose services to avoid "heavy" model handler replacements. It is easier to replace/override a particular service than a whole bunch of model handlers.
