### ISSUE TITLE
Missing property Hidden for ContentEditorWebPart

### ISSUE THREAD

**Issue by andreasblueher** [SubPointSolutions/spmeta2#1042]
Hello,

I'm missing the option to hide content editor webparts after adding them to my site. This editor webpart contains only JavaScript code and therefor doesn't need to be visible on the site. Since every webpart has this property, I'm wondering if I should create a pull request for changing WebPartDefinitionBase accordingly?

**Comment by SubPointSupport** [comment]
That could be all about the chrome/border properties, but we'll have a closer look on this. Most likely, we will have to add a new property to map .Hidden across the board. WebPartDefinitionBase might be a good place.

We'll go that, no need for PR. What's your urgency, when do you need this one?

**Comment by andreasblueher** [comment]
Hey guys, don't get me wrong but wouldn't this be a great example for someone like me oder one of my teammembers to implement something rather easy in SPMeta? Of course doing it yourself is the way to get exactly what you're looking for, but maybe having more people contributing is a good thing anyway.

Since you added this to milestone 1.2.130 too and the fact you didn't release it end of last week, any new date on the release?

**Comment by SubPointSupport** [comment]
The problem is that easiness of this particular thing is heavily underestimated. Here are more details on the web parts.

With the web parts, SharePoint has tons of places to deploy it to: wiki, web part, publishing pages, then new/edit/display forms in libs/lists, the list view pages in both lists/libs, then pages in the content types. Altogether, more than 10+ places top deploy the web part to.

Apart that, some web part work differently deployed under the root web, or the web sub (ListViewWwebPart). SPMeta2 regression testing covers that - from initial testing, random web part deployments to all pages, and then all the web part definitions to all the possible pages under the root web and the sub web. 

Our setup for regression testing has 8-12 SharePoint 2013 farms, full regression testing over CSOM/SSOM across all 1000+ tests even with NCrunch takes a few hours altogether.

Not that we aren't happy with the contribution, but rather that we locked ourselves with the complexity to guarantee the quality. Such testing takes time and effort, and we have been having some relatively "simple" PRs which turned out to be quite disastrous failing dozens tests here and there.

As for the missing releases, haven't been having major issue/feature requests over the last several months. Hence the decline in both development and release cycles. The pace is getting fixed at the moment.

**Comment by SubPointSupport** [comment]
In progress.
