### ISSUE TITLE
Definitions for SharePoint 2016 Suite Bar

### ISSUE THREAD

**Issue by andreasblueher** [SubPointSolutions/spmeta2#1052]
Hello,

I was wondering if you're planning to add suite bar support to SPMeta?

https://code.msdn.microsoft.com/office/SharePoint-2016-SuiteBar-9f9d8304#content

I would like to add them to my pool of definitions :)

**Comment by SubPointSupport** [comment]
With the recent release we added SuiteNavDefinition:
https://github.com/subpointsolutions/spmeta2/issues/852

It needs some love to make it work with SharePoint 2016 due to new props introduced. if-def conditions might help but it must work well for both SP2016 and SP2013 using new props or failing back and skipping props which aren't available in SP2013. 

Have a look, let us know what is missed. It's relatively small fix, SSOM only, straight props and implementation. The heavy lifting was already done.

**Comment by SubPointSupport** [comment]
@andreasblueher, just checking on this one. Would you be keen to enhance this definition or at least feedback on the missing properties so that we can add them?

**Comment by andreasblueher** [comment]
Tbh I was expecting way more from SuiteNav elements than Microsoft implemented. I hoped to be able to add tiles to the "365 like navigation" in the upper left corner, but it appears that's not what SuiteNavDefinition is for. 

In addition to my not fulfilled expectations I'm really wondering why I would want to define my SuiteNav on WebApplication level? Wouldn't it make more sense to have this kind of settings on sitecollection level? Maybe even SPWeb?

We found a way to use JavaScript to add tiles having a MicroServices which ultimately is what I was trying to do. Too bad Microsoft allow this to be done through other code. From my point of view, you can close this issue.

**Comment by SubPointSupport** [comment]
Agree on everything said.
