### ISSUE TITLE
C#/.NET version for compatibility reasons

### ISSUE THREAD

**Issue by andreasblueher** [SubPointSolutions/spmeta2#1058]
Hey,
nothing urgent here just checking if you got plans on how long you want to keep supporting SP2010/.NET 3.5 or if you might at one point leave 3.x behind and upgrade your solutions to 4.6?

**Comment by SubPointSupport** [comment]
Current dev env looks pretty old:
* VS2013 SP4 (due to some changes in mvc web apps we've got issue migrating solution to VS2015/2017)
* SharePoint 2013 SP1

Migration to SP2016/VS2015-17 is on the radar, gonna happen over the following month. There are a few pending things to be done.

As for the SP2010/NET35 usage, totally understand the concern. It holds us on pretty old C# and .NET version itself. We aren't in a position to figure out the cut off yet. Will be running some surveys close to the end of the year to see what's there for SP2010. Clearly, it's on the way out after 7+ years, SPMeta2 usage on SP2010 is relatively small and decreasing.

The bigger question for us is how we going to maintain this stuff - making a branch, moving forward with SP2013+ stuff and leaving behind SP2010 as a separate branch or having it all in the same one increasing the complexity with "if-def" things. That's an open question yet as well.
