### ISSUE TITLE
Can't add PeoplePickerSettingsDefinition to SPWebApplicationModel

### ISSUE THREAD

**Issue by andreasblueher** [SubPointSolutions/spmeta2#1059]
Hey,

after creating a PR for PeoplePickerSettings almost 1,5 years ago I finally got to the point to use it 🎉 but it didn't work as expected.

I looked into the code and compared PeoplePickerSettingsDefinition with AlternateUrlDefinition (which to me is almost the same) and found the reason why. I'll create a PR for this and link it to this issue.

### Brief description
Please provide short description covering two areas:
* expected behaviour: AddPeoplePickerSettings should be available for WebAppModel
* actual behavior: AddPeoplePickerSettings is not available

### SharePoint API
Which version of SharePoint runtime do you use? 
* SSOM SP 2016 CU July 2017

### SPMeta2 API
1.2.130

### SPMeta2 model
Optionally, provide SPMeta2 model in which issue occurs. That helps to identify the issue and provide the solution as far as we can.
```cs

public static PeoplePickerSettingsDefinition PeoplePickerSettingsDefinition = new PeoplePickerSettingsDefinition
{
  OnlySearchWithinSiteCollection = true,
  PeopleEditorOnlyResolveWithinSiteCollection = true
};

var webAppModel = SPMeta2Model.NewWebApplicationModel(webApp =>
                    webApp.AddPeoplePickerSettings(Definitions.WebAppDefinitions.PeoplePickerSettingsDefinition));
```

**Comment by SubPointSupport** [comment]
What's wrong with it? We've got regression testing on that, what's missing?

**Comment by SubPointSupport** [comment]
Ouch, so IModuleFileHostModelNode -> IWebApplicationModelNode. Tests didn't catch that, only the presence of .AddPeoplePickerSettings() extension methods. Looking deeper into host objects and interfaces is possible but probably too much. We don't expect many more definition any time soon.

Closing. Fixed by @andreasblueher in Change PeoplePicketSettingsSyntax so AddPeoplePicketSettings is avail… #1060
