### ISSUE TITLE
FieldDefinition ignores InternalName

### ISSUE THREAD

**Issue by Ridlsan** [SubPointSolutions/spmeta2#1073]
I have russian locale. When i provision field like in example below, spmeta2 ignores InternalName and creates field with internal name like "_x0417__x043d__x0430__x0447__x04"
var weight = new FieldDefinition()
            {              
                InternalName = "weight",
                Title = "Значимость",
                FieldType = BuiltInFieldTypes.Text,
                Id = new Guid("8E562E81-B8F1-49DD-87DB-B7EEC77DC3C7")
            };
How to fix: At the begining It shoud create field with internal name, then change Title

**Comment by SubPointSupport** [comment]
@Ridlsan, thanks for raising this one, appreciate that.

Most likely, this field gets added to a list (is that right?). In such scenarios, additional property needs to be set to make SharePoint using InternalName. The following one should solve the problem but redeployment of the model (with the field) is required. Remove the field from the list and get another deployment going.

`
AddFieldOptions = BuiltInAddFieldOptions.AddFieldInternalNameHint solve this problem, thank you.
`

Let us know how it goes and is there is anything else we can help with.

**Comment by Ridlsan** [comment]
Yeah, it works, thank you!

**Comment by SubPointSupport** [comment]
No worries :)

**Comment by vladivanovrf** [comment]
Can we set more than one "AddFieldOptions"?
For example, add to one field two options:
**AddFieldOptions = BuiltInAddFieldOptions.AddToAllContentTypes**
**AddFieldOptions = BuiltInAddFieldOptions.AddFieldInternalNameHint**

**Comment by avishnyakov** [comment]
No, @vladivanovrf, unfortunately we can't. This is a "bug", more of a misdesign, overlooked decision made long time ago. We had a similar problem with ListViewDefinition, solved with a new property.

We need to introduce a new property which would an array of values so that we can handle this case. New property needs to be there for a backward compatibility with already existing models and deployments.

Would you please raise a new ticket for this?

**Comment by vladivanovrf** [comment]
Ok, I'll do it
