### ISSUE TITLE
SPMeta deprecated

### ISSUE THREAD

**Issue by andreasblueher** [SubPointSolutions/spmeta2#1125]
It has been a year since I created #1080 after which it took you another 6 month to release 1.2.140 in February. Another 7 month have gone by and beside some other discussions from my side, nothing has changed/happened. All the promises/commitments you made were broken. It has come to the point that for the 3 PRs I created I'm currently using a custom build with 2 of my customers.

I'm not gonna repeat all the good things about SPMeta, how much I digged this project and I'm really sad it has come to this point, but I'm regretting not choosing PnP over SPMeta a few years back.

The fact that I'm the only one complaining here and that there's no development towards SPO and SP2016 should have be a big warning to me a year ago, but sometimes you have to learn the hard way. 

Cheers and all the best

**Comment by SubPointSupport** [comment]
Thanks, @andreasblueher , noted.

We haven't seen much feedback on needed features, it's pretty stable and hence no active dev was done. What else apart (1) SP2016 support and (2) active dev is needed from your view?

**Comment by andreasblueher** [comment]
I created 3 PRs (#1123 is crucial, while the other two are low priority) in July with a required feature which I started/developed myself for which I haven't gotten any reply.

We've talked about this several times (reference #1088) and I've stated more than once what I'm looking for. I don't see the point in repeating myself, if nothing changes. For example you commited on releasing information on a regular basis (see 1088) and there hasn't been a single post on https://medium.com/@subpointsocial. You have twice confirmed merging the PRs and yet nothing has happened.

@koltyakov could you please explain why you put a thumbs up on SubPointSupport reponse? Do you think I'm out of line here?

**Comment by koltyakov** [comment]
Hi @andreasblueher,

Oh, can't provide you a short answer, so a long one. 

We've been using M2 for a pretty long time (30 plus something relatively large projects or even more, some of them are really massive with 3000-4000 artifact nodes), I know people behind the tool in person, also I know what is to maintain an opensource project. Some insides might give an overview and extra empathy.

We went through different challenges with M2 and survived. It takes place in current On-Prem projects, solves the task it was implemented for.

I have not checked the issues and PRs from you, I believe they are important. Every team applies their own approaches and over time the route which is being taken is safe to go. I can confirm that we’re not experiencing any dramatic issues with M2, it’s just stable it just works in the scopes of On-Prem solutions. With SPO especially its modern part is a bit different story, but there is no silver bullet, only combinations and compromises, and decisions for a specific case. That’s why we’re are not strangers to PnP Provisioning too. Love them both and use them both taking the best parts of the tools based on tech requirements and circumstances. 

So, I agree with @SubPointSupport on the stability of M2 in the most of the scenarios. My thumb up is to cheer up guys. At the same time, I’m not saying that the communication gaps and transparency loss is a good thing, yet I feel why it could be happening. And I firmly believe it’s just a priority weights juggling issue while making great steps in overall offer strategy missing smaller breaches due to limited resources. Opensource is in general volunteering without SLA. Even if a response is so important to rely on the tool and decide to use it or not. Yep, that's risks, that's opensource.

I do believe and hope guys will improve communications and increase their activity on M2. And personally, ready to give them more and more chances for it. ❤️

So that’s why was that thumb up.

@andreasblueher, I hope you'll be helped with your issues as well.

**Comment by andreasblueher** [comment]
Hey @koltyakov,

I've contributed to this project several times in the last years. I might not have 20-30 projects on M2, but I have projects in the region of 3000 artifacts myself and every SharePoint Project is based on M2. While my tone might sound harsh (might be intended this time) you can read #1088 and see that I've always been very understanding and I've awalys asked @SubPointSupport to simply tell that there're more important things on their agenda as of right now.

However, for 3 or 4 times I've gotten the response, that things will change, a,b,c are topics which they've been working on and that communication will improve in the near future. This never happened and that's the main reason behind my post today.

I truly beleave in Open Source and I don't think I've asked too much. Software which is not being maintained anymore is dead/will die. If I wouldn't have requested/pushed the 1.2.140 release in February who knows we might still be on 1.2.130. There are several commits including a fix for #1101, #1087 and #1118 already in dev and from an outsiders view there is no indicator why they're not being released. Also quiet a few requests and ideas from users are in the issue list including some I brought to this project to improve M2.

We're talking about pretty much one year where I asked several times nicely (at least that was my intention) and even after all that I cannot thank you enough for your M2 because before that developing SharePoint was even more pain that it is by default ;-)

**Comment by andreasblueher** [comment]
16 days, no word, no action.
