### ISSUE TITLE
Add 'localization' support for particular artifacts

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2#257]
It would be nice to provision some artifact with localization support.

There is an API which allows to setup labels/titles and other properties in several locales, so would be nice to streamline it into SPMeta2.

SetValueForUICulture() method needs to be used.
http://sharepoint.stackexchange.com/questions/35914/how-do-i-change-the-title-column-of-a-list-programmatically

### implementation
Additional properties TitleResource and DescriptionResource are to be added to the appropriate definitions. These properties should be lists of ValueForUICulture object:

```
 public class ValueForUICulture
    {
        #region properties

        [DataMember]
        public int? CultureId { get; set; }

        [DataMember]
        public string CultureName { get; set; }

        [DataMember]
        public string Value { get; set; }

        #endregion
    }
```

The following artefacts should support localization:

* [SSOM/CSOM] SPWeb
* [SSOM/CSOM] SPField
* [SSOM/CSOM] SPContentType (NameResource!)
* [SSOM/CSOM] SPList
* [SSOM/CSOM] SPView
* [SSOM/CSOM] SPNavigationNode
* [SSOM/CSOM] SPUserCustomAction

All test should be written accordingly per every mentioned artifact under Regression.Scenarios.XXX.Localization category.

**Comment by MarkusJenni** [comment]
After a short look at the current solution i would proceed with the following steps to introduce localization support:
* Adding a new TitleResoureDefinition to the Core Definitions. The Definition contains two properties, CultureName and Value, where CultureName is in the syntax like "en-us", "de-de" ect.
* Allow to add one or more TitleResourceDefinitions to the following artefacts:
 * SPWeb
 * SPField
 * SPContentType (NameResource!)
 * SPList
 * SPView
 * SPNavigationNode
 * SPUserCustomAction
* Create ModelHandlers for SSOM and O365. For CSOM (based on Version 15 assemblies) the TitleResource Property is not yet exposed. It would be nice to have a ModelHandler for CSOM which logs a warning that setting the TitleResource is only possible with O365 or SSOM.

* Add a new DescriptionResourceDefinition to the Core Definitions. The Definition contains the same properties as the TitleResourceDefinition.
* Allow to add one or more TitleResourceDefinitions to the following artefacts:
 * SPWeb
 * SPField
 * SPContentType
 * SPList
 * SPUserCustomAction

Both TitleResourceDefinition and DescriptionResourceDefinition should derive from a base class. For instance UserResourceDefinition as it is the SP object model

**Comment by andreasblueher** [comment]
I've got a few things to add and would love to talk about and support you with this if possible. 

First of all be aware when you try to set the "Title" property for the default language pretty strange things can happen (at least for Fields in SSOM). Please refer to this [link](http://sharepoint.stackexchange.com/questions/24163/how-to-rename-title-column-in-document-library-using-code) and the answer from Anders Rask. We had to change the current thread culture to get it working in a multilingual environment. I don't know about CSOM and O365, I suppose they should be working without any issue.

Second I would love to be able to simply hand over the resourcename+resourcefile and the handler would go ahead and set the titleresource for every supported language. Even if the web would have more cultures in SupportedUICultures than actual resource files existed it could always fall back to the default resource file. Having to set resourcevalue and culture would be a big overhead when you got 5 supported languages. If you hand over the name of the resource and the filename, all required information would be available.

I have no idea how you could do that, but maybe you could offer both approaches since many people will have no more than 2 supported languages.
