### ISSUE TITLE
Can't find model handler for type TaxonomyTermStoreDefinition

### ISSUE THREAD

**Issue by avaranovich** [SubPointSolutions/spmeta2#294]
The basic taxonomy store provisioning code 

```cs
  var siteModel1 = SPMeta2Model
                              .NewSiteModel(site =>
                              {
                                  site.AddTaxonomyTermStore(TermModels.termStore, store =>
                                           store.AddTaxonomyTermGroup(TermModels.XYZ, g=> 
....
```

throws an exception

Application: Parameter name: Can't find model handler for type:[SPMeta2.Standard.Definitions.Taxonomy.TaxonomyTermStoreDefinition]. Current ModelService type: [SPMeta2.CSOM.Services.CSOMProvisionService].

**Comment by O365Tycho** [comment]
The same (sort of) issue applies to the provisioning of Taxonomyfields:

Application: Parameter name: Can't find model handler for type:[SPMeta2.Standard.Definitions.Fields.TaxonomyFieldDefinition]. Current ModelService type: [SPMeta2.CSOM.Services.CSOMProvisionService]

**Comment by SubPointSupport** [comment]
Hello O365Tycho and avaranovich,

Thank you for the feedback, appreciate that.

SPMeta2 does not know about "standard" provision handlers. It does not know how to provision definitions from SPMeta2.Standard.dll. It is done intentionally to decouple foundation/standard SP features into separate assemblies.

To change that, we need to register all "standard" model handlers calling the following method:

var provisionService = new CSOM/SSOMProvisionService()

// call this one, we need to register additional handlers
provisionService.RegisterModelHandlers(typeof(TaxonomyTermModelHandler).Assembly); 

/// provision your model here

TaxonomyTermModelHandler - pick the one from SSOM/CSOM dll, and pass the assembly into RegisterModelHandlers() method. It gets all model handlers and adds to SPMeta2 so that it is able to provision "standard" things.

It has not been documented yet.

Also, with January 2015 release, we are going to introduce StandardXXXProvisionService' for SSOM/CSOM - https://github.com/SubPointSolutions/spmeta2/issues/292
So that you would use StandardCSOMProvisionService/StandardSSOMProvisionService for all 'standard' artefact provision.

Let me know how it goes, and if there is anything else we might help you with.
Also, don't hesitate to join our yammer group - https://www.yammer.com/spmeta2feedback

Cheers, and enjoy the rest of the day.

**Comment by O365Tycho** [comment]
Hello SubPointSupport,

I've added the handlers so we now have 
var csomProvisionService = new CSOMProvisionService();
csomProvisionService.RegisterModelHandlers(typeof(TaxonomyTermStoreModelHandler).Assembly);
csomProvisionService.RegisterModelHandlers(typeof(TaxonomyGroupModelHandler).Assembly);
csomProvisionService.RegisterModelHandlers(typeof(TaxonomyTermSetModelHandler).Assembly);
csomProvisionService.RegisterModelHandlers(typeof(TaxonomyTermModelHandler).Assembly);
csomProvisionService.DeployModel(SPMeta2.CSOM.ModelHosts.SiteModelHost.FromClientContext(clientContext), siteModel);

And the it doesn't give the exception about the missing handler anymore. But unfortunately i do get 
"Fail: Exception has been thrown by the target of an invocation." . 

Any idea's what might cause this? 

ps. looks like the TaxonomyGroupModelHandler has been forgotten in the renaming process.

**Comment by SubPointSupport** [comment]
Please use te following code to register all "standard" model handler:

var provisionService = new CSOM/SSOMProvisionService()
provisionService.RegisterModelHandlers(typeof(TaxonomyTermModelHandler).Assembly);

provisionService .DeployModel(SPMeta2.CSOM.ModelHosts.SiteModelHost.FromClientContext(clientContext), siteModel);

This registers all model handler which can be found in the target assembly.

As for the exception, what's the stacktrace, what;s the message, how the model looks like?
Is it SSOM/CSOM? 
If CSOM, then do you use v15 or v16 client assemblies?

**Comment by O365Tycho** [comment]
The Model 
```cs
public static TaxonomyTermStoreDefinition termStore = new TaxonomyTermStoreDefinition
{
   UseDefaultSiteCollectionTermStore = true
};

public static TaxonomyTermGroupDefinition Beeldbank = new TaxonomyTermGroupDefinition
{
  Name = "Beeldbank"
};

var siteModel1 = SPMeta2Model
                              .NewSiteModel(site =>
                              {
                                  site
                                   .AddTaxonomyTermStore(TermModels.termStore, store =>      
                                           store.AddTaxonomyTermGroup(TermModels.Beeldbank));
                              });

DeploySiteModel(siteModel1);
```

I've now used the code you suggested to register the handlers and it errors out in the RegisterModelHandlers function with the following innerexception:
```cs
The type initializer for 'SPMeta2.CSOM.Standard.ModelHandlers.Taxonomy.TaxonomyTermStoreModelHandler' threw an exception.
   at SPMeta2.CSOM.Standard.ModelHandlers.Taxonomy.TaxonomyTermStoreModelHandler..cctor()
Could not load file or assembly 'Microsoft.SharePoint.Client.Taxonomy, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c' or one of its dependencies. The system cannot find the file specified.
```

**Comment by SubPointSupport** [comment]
Is 'Microsoft.SharePoint.Client.Taxonomy' assembly added to the VS project?

**Comment by O365Tycho** [comment]
yes. v15.

**Comment by SubPointSupport** [comment]
Will follow up this today with working VS sample project.

**Comment by SubPointSupport** [comment]
Closing this issue.

RegisterModelHandlers() should be used to register standard provision handlers.
provisionService.RegisterModelHandlers(typeof(TaxonomyTermModelHandler).Assembly);

With January 2015 release, StandardXXXProvisionService' for SSOM/CSOM should be used.

For the fuhrer issues please join our Yammer network - https://www.yammer.com/spmeta2feedback - or create a separate ticket.

Thanks!
