### ISSUE TITLE
Enhance 'ModuleFileDefinition' - implement "add to web" scenario

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2#377]
The following provision scenarios need to be covered by regression tests:

* Deploy module file to web

Ref:  https://github.com/SubPointSolutions/spmeta2/issues/289

**Comment by antonkhrit** [comment]
Is it implemented? I saw NotImplementedException there. 
Best regards
Anton Khritonenkov
Plumsail Team
http://plumsail. com


-------- Original Message --------

**Comment by SubPointSupport** [comment]
Not, it is not implemented yet. This is a rare case, as module file is deployed outside of the library, straight to the web. Should not be used in production.

Created this ticket to keep tracking.

**Comment by antonkhrit** [comment]
It can be quite useful for provision of custom list views. Instead of creation of view and modification of it’s as page we can prepare ready for use view with custom web parts, markup, etc. and provision it as simple .aspx file (with tokens resolving like ListId, ViewId, etc). This can save a ton of time. This is just my case.

**Comment by SubPointSupport** [comment]
Adding a module file to a web has nothing to do with the case you described.

However, could you provide more details on your case?
Sound like you want to provision a page under "Forms" library as a new view without creating a new view, correct?

**Comment by antonkhrit** [comment]
I don’t see any difference. I meant provision of any file outside of document library. You can do this with typical module (declarative deployment). I just described how I could use it. In my case I want to deploy aspx.page in the root folder of list. Before provision I could replase some tokens inside page. If you add aspx page with XsltListViewWebPart and View tag inside list you will get working view. I preffer such provision because I can simply create View with complex HTML on my Dev environment. Then copy it though SharePoint Designer, replace some tokens (ListID, VIewId, etc).

 

Another case where I will use this for sure, deployment of custom forms also inside SharePoint list.

**Comment by SubPointSupport** [comment]
Understood, thanks for the context.
