### ISSUE TITLE
[Help Needed] SPMeta2 Ecosystem icon/font set

### ISSUE THREAD

**Issue by avishnyakov** [SubPointSolutions/spmeta2#56]
We are making serious stuff. Icon just a must have.

**Comment by SubPointSupport** [comment]
Left for the future R&D.

**Comment by SubPointSupport** [comment]
Done.

https://twitter.com/spmeta2
https://pbs.twimg.com/profile_images/566496790430511104/dPmlsFDc_400x400.png

**Comment by SubPointSupport** [comment]
Reopening this ticket, looking for some input and help to get SPMeta2 Ecosystem shaped up.

It would be nice to have a consistent icon or font set across all current API projects as well as an easy way to plug a new project into the family (so that we won't have to come up with a new design or something, avoid spending tons of time and effort). 

Currently, we've a bunch of APIs to simplify SharePoint related development:
* build, deployment
* packaging and distribution 

Here is the current set of APIs, build/dev and package/distribute, which currently drive the whole SPMeta2 ecosystem. Docs are being redesign and rewritten that way as well.

#### Build and Deploy
* SPMeta2 - artifact provision for SharePoint
* SPMeta2 VS Extensions - Visual Studio extensions for SPMeta2
* SPMeta2 Reverse - a library to reverse engineer SharePoint web sites into SPMeta2 models
* SPMeta2 Specs - a library to produce documentation based on existing SPMeta2 models
* reSharePoint - a ReSharper plugin to write SharePoint code faster and better

#### Package and Distribute
* MetaPack - a NuGet based API to package, distribute and deploy SharePoint customization, it actually comes in API, CLI and Desktop Client
* MetaPack Gallery - NuGet based gallery for community packages ( http://metapackgallery.com )
* DefinitelyPacked - a community repo for metapack packages 

Other tooling is to be outside of SPMeta2 ecosystem being fully commercial.

**Comment by SubPointSupport** [comment]
Implemented. Will be pushed with the new docs and branding.
