### ISSUE TITLE
UserCustomActionDefinition doesn't take absolute urls for ScriptLink types

### ISSUE THREAD

**Issue by davesmits** [SubPointSolutions/spmeta2#756]
take this code:
public static UserCustomActionDefinition jqueryRegistration = new UserCustomActionDefinition
        {
            Title = "jQuery",
            Name = "jQuery",
            ScriptSrc = "https://sparked-beeldbank.azurewebsites.net/Content/Scripts/imagelibrary",
            Location = "ScriptLink",
            Sequence = 100
        };

SPMeta2 crashes because the url isnt using token. It requires me to deploy the javascript to the style library. Not helpful, requires more maintaince. better and easier so can use CDN's

**Comment by SubPointSupport** [comment]
Correct, M2 has built-in validation to prevent full urls in the UserCustomActionDefinition.ScriptSrc 

Here are mode details on the ticket:
Enhance 'UserCustomAction' provision - add valiation in ScriptSrc prop 
https://github.com/SubPointSolutions/spmeta2/issues/672

In nutshell, full URL in the user custom action puts SharePoint down, so that it gives a weird blank screen. That's been reported over and over, and was hard to fix/troubleshoot. So we added the validation in the recent M2 releases.

Here is a sample - "When publishing a custom action for registering jQuery or another external script via ScriptLink, you might get a blank white page."
https://blog.lekman.com/2013/01/scriptlink-registration-in-sharepoint.html 

Hope that provides more visibility on the issue, and the reasons why we decided add validation and prevent full urls in the user custom actions.

Cheers!

**Comment by davesmits** [comment]
Thanks. It's funny. i have the white page now too when using CSOM to create customactions outside the sitecollection while a collegue is doing this for other an other project without issue. But thanks for clarifications

**Comment by SubPointSupport** [comment]
Well, there is an option to disable validation on full URLs. Would not recommend that due to absolutely unpredictable outcomes. Too hard to debug and fix. Maybe JS loaders will do?

Anyway, closing that one. Let us know if there is anything else we can do.
Cheers!
