### ISSUE TITLE
Enhance ContentTypeDefinition - support Name renaming

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2#924]
### Brief description

SPMeta2 should support content type Name renaming.

Model with ContentTypeDefinition should be deployed correctly over ContentTypeDefinition.Name changes. M2 should deploy a new content type, and then update existing (fetching by ID) with the new name.

SP2013 CSOM/SSOM should be supported.
SP2010 should have limited support with CSOM as there is no way to create a content type with prefedined ID. It should fallback on Name based resolution so that renaming won't be supported.

Regression tests must be written to ensure this feature.

**Comment by SubPointSupport** [comment]
Implemented with CanDeploy_ContentType_And_Rename tests, no issues found.
Waiting for the client's feedback.

**Comment by DmitryDruzhkov** [comment]
As a result of the analysis, it was found that the problem is with the updating of the content type has been associated with the mismatch in the version of SharePoint test environment, the declared minimum requirements (SharePoint 2013 with Service Pack 1). In similar operations on a supported environment error does not occur.

**Comment by SubPointSupport** [comment]
Sweet, closing. Thanks for your effort and time to get it tested, appeciate that.
