### ISSUE TITLE
Missing TopNavigationNodeDefinition Syntax for RootWebModelNode

### ISSUE THREAD

**Issue by adaoust** [SubPointSolutions/spmeta2#953]
Hi @SubPointSupport,

It works with `rootweb.AddDefinitionNode(new TopNavigationNodeDefinition())`, but the nicer syntax provided by extensions doesn't allow the definition to be added to a `RootWebModelNode`.

Thanks,

Alex

**Comment by SubPointSupport** [comment]
Make sense. We'll extend syntax around RootWeb to mimic same behavior as WebDefinition.

Just curious on the usage, do you add some changes to the root web while provisioning subweb? What are they, how all it works for you?

**Comment by adaoust** [comment]
Hi @SubPointSupport,

Thanks for doing this!

To answer your question; I use the SiteModel even for the root web because I currently generate the models dynamically instead of using static definitions. This allows me to read the data/definitions from a database and build the model from those. This allows me to reuse the same model generation code, but with different datasets. With that being said, it is easier to put everything in the same SiteModel (Single Model) rather than having multiple WebModels. This also makes it easier to serialize to JSON and do parameter substitution if I want to deploy to different environments. 

Thanks,

Alex

**Comment by SubPointSupport** [comment]
Sure, no worries. Interesting case, glad it works well for you. 

Also, a big "thank you" for the recent O365 v16.1 issue report. The issue was much more bigger than we could ever imagine, and we wouldn't have found it without your help. Fixed, testing and will push a new shiny release with all your reports inclusing this:
Missing SiteLogoUrl and other props under O365 16.1 runtime #939

Thanks again and keep up a great job!, @adaoust :)
