### ISSUE TITLE
Adding remote event receiver provisioning 

### ISSUE THREAD

**Issue by avishnyakov** [SubPointSolutions/spmeta2#98]
SPMeta2 should support remove event receiver provision.

http://andrewwburns.com/2014/01/10/register-remote-event-receivers-on-the-host-web/

**Comment by maratbakirov** [comment]
Would be really nice to have it!

**Comment by maratbakirov** [comment]
Based on this article https://andrewwburns.com/2014/01/10/register-remote-event-receivers-on-the-host-web/ we should also think about remove action. 

quote:
This removal of remote event receiver registrations is actually pretty important. It turns out that you can’t remove those registrations with, say, a console application and some C# client-side object model code – you’ll just get an error “Access Denied”. It appears that only the app itself can remove it’s own event receiver registrations. This makes sense – you don’t want other scripts/apps removing the event receivers your solution relies on. However, I think it could lead to a lot of orphaned event receivers if people just follow Johnny’s example, and don’t tidy up after themselves. Certainly, there are a few people asking about it and I believe the following:

I’ve been in touch with someone at Microsoft. He said the behaviour was as-designed and that a remote event receiver could only be removed by the app that added it.

**Comment by SubPointSupport** [comment]
Sure, makes sense. 

Still holding back. No one really asked for this feature for nearly two years. We'll see what can be done once we've got more requests to implement this one.

**Comment by SubPointSupport** [comment]
Closing due to lack of popularity. Moving to Nice-To-Have.
