### ISSUE TITLE
ListViewWebPartDefinition doesn't show calendar view

### ISSUE THREAD

**Issue by ReDERO** [SubPointSolutions/spmeta2#988]
### Brief description
Hello, we want to create standart webpart page, that contains calendar list view. But after provision webpart shows default list view.

### SharePoint API
O365

### SPMeta2 API
```cs
SPMeta2.Diagnostic.DiagnosticInfo SPMeta2FileVersion:[1.2.17057.1048] SPMeta2FileLocation:[C:\Users\abog\Projects\Intranet Portal UA\Sources\IntranetPortalUA\IntranetPortalUA.Department\bin\Debug\SPMeta2.dll] CSOMFileVersion:[16.1.5715.1200] CSOMFileLocation:[C:\Users\abog\Projects\Intranet Portal UA\Sources\IntranetPortalUA\IntranetPortalUA.Department\bin\Debug\Microsoft.SharePoint.Client.dll] Convert(p.IsSSOMDetected):[False]
```

### SPMeta2 model
```cs
public class DepartmentWebModel
    {
        public static ContentTypeDefinition DepartmentEvent = new ContentTypeDefinition
        {
            Id = new Guid("193dc6b1-cc8d-4d95-95cd-f881bc20847d"),
            Name = @"Подія департаменту",
            Group = @"Portal",
            ParentContentTypeId = SPMeta2.Enumerations.BuiltInContentTypeId.DocumentSet_Correct,
        };

        public static ListDefinition DepartmentEvents = new ListDefinition
        {
            Title = @"Події департаменту",
            Description = @"Події департаменту",
            CustomUrl = @"Lists/DepartmentEvents",
            TemplateName = BuiltInListTemplates.DocumentLibrary.InternalName,
            ContentTypesEnabled = true,
        };

        public static ListViewDefinition DepartmentEventsCalendar = new ListViewDefinition
        {
            Title = @"Календар",
            Url = @"Calendar.aspx",
            RowLimit = 0,
            Query = @"<Where>
                        <DateRangesOverlap>
                            <FieldRef Name=""StartDate"" /><FieldRef Name=""_EndDate"" />
                            <Value Type=""DateTime""><Month /></Value>
                        </DateRangesOverlap>
                    </Where>",
            IsPaged = false,
            IsDefault = false,
            Fields = new System.Collections.ObjectModel.Collection<string> { SPMeta2.BuiltInDefinitions.BuiltInFieldDefinitions.StartDate.InternalName, SPMeta2.BuiltInDefinitions.BuiltInFieldDefinitions._EndDate.InternalName, SPMeta2.BuiltInDefinitions.BuiltInFieldDefinitions.Title.InternalName },
            Type = @"Html",
            Types = new System.Collections.ObjectModel.Collection<string> { "Calendar", "Recurrence" },
        };

        public static WebPartPageDefinition Home = new WebPartPageDefinition
        {
            CustomPageLayout = CustomMarkups.CustomWebpartPageMarkup,
            Title = @"Головна",
            FileName = @"Home.aspx",
        };

        public static ListViewWebPartDefinition Calendar = new ListViewWebPartDefinition
        {
            ListTitle = DepartmentEvents.Title,
            ViewName = DepartmentEventsCalendar.Title,
            ChromeType = @"Default",
            Title = @"Календар подій",
            Id = @"Calendar",
            ZoneId = @"LeftColumn",
            ZoneIndex = 0,
        };

        public ModelNode GetSiteModel()
        {
            var model = SPMeta2Model.NewSiteModel(site =>
            {
                site
                    .AddContentType(DepartmentEvent, contentType =>
                    {
                        contentType
                            .AddContentTypeFieldLink(SPMeta2.BuiltInDefinitions.BuiltInFieldDefinitions.Title)
                            .AddContentTypeFieldLink(SPMeta2.BuiltInDefinitions.BuiltInFieldDefinitions.StartDate)
                            .AddContentTypeFieldLink(SPMeta2.BuiltInDefinitions.BuiltInFieldDefinitions._EndDate);
                    });
            });

            return model;
        }

        public ModelNode GetWebModel()
        {
            var model = SPMeta2Model.NewWebModel(web =>
            {
                web
                    .AddList(DepartmentEvents, list =>
                    {
                        list
                            .AddContentTypeLink(DepartmentEvent)
                            .SetDefaultListContentType(DepartmentEvent)
                            .AddListView(DepartmentEventsCalendar);
                    })
                    .AddHostList(SPMeta2.BuiltInDefinitions.BuiltInListDefinitions.SitePages, list =>
                    {
                        list
                            .AddWebPartPage(Home, page =>
                            {
                                page.AddWebPart(Calendar);
                            });
                    });
            });

            return model;
        }

        public void DeployIntranet(ClientContext context)
        {
                this.DeployWebModel(context, GetSiteModel());
                this.DeployWebModel(context, GetWebModel());
        }
    }
```

**Comment by SubPointSupport** [comment]
The model looks good, all should be working fine.

We guess that it could be all about .ViewDaa property of the target view. The following examples illustrates how to get started and setup correct values for both .Query and .ViewData properties:

CanDeploy_ListView_AsCalendar
https://github.com/SubPointSolutions/spmeta2/blob/f85e05e46f3573f50d7ddb5ed2633c7e83383ac9/SPMeta2/SPMeta2.Regression.Tests/Impl/Scenarios/ListViewScenariousTest.cs

We'll have a closer look this week as well.

**Comment by SubPointSupport** [comment]
@ReDERO, in progress. What's the ETA you need?

**Comment by SubPointSupport** [comment]
Confirming the issue. Somehow, ListViewWebPart can't be connected with a custom created calendar view under CSOM. SSOM works well.

Checking why, trying to find solution.

**Comment by SubPointSupport** [comment]
Unsupported for CSOM.

The issue has to do with a specific behavior of ListViewWebPart under CSOM based provision.
Both ListViewWebPart/XsltListViewWebPart get the default list view in the list attaching itself to it under CSOM provision. Currently, SPMeta2 has a built-in workaround - before such a web part gets provisioned, SPMeta2 sets the target view as a default view in the list, then provisions the web part (so that web part gets the right list view from the default list view), and then resets default list view to the old one. It works well even for the event list, so that ListViewWebPart can be correctly attached to a custom list view in the calendar view.

Now, why it does not work for the suggested scenario? We think that the problem has to do with a list view property "BaseViewID". For a calendar list (event list), all views have BaseViewID = 2, whereas for a document library all view would have BaseViewID = 1. We've got a strong guess that ListViewWebPart under CSOM provision not only gets the default view from the list but also default view's BaseViewID. It's all good with the event lists (BaseViewID = 2) but it is always BaseViewID = 1 for document libraries.

We can't really see much options apart dropping this one with "unsupported" status, really sorry for this. Also, PnP seems to have similar ticket reported:
- Provisioning engine does not set the correct view on Calendar web part #380
https://github.com/SharePoint/PnP-Sites-Core/issues/380

Having said that, there is a tricky possibility to get the right outcome. The flow might look as following:
- We need to get list view with BaseViewID = 2 before provisioning ListViewWebPart, sooo...
- Deploy XsltListViewWebPart wth .XmlDefinition = "<View BaseViewID='2'/>" - it would create a list view with BaseViewID=2 (we think it would but would it?
- Delete XsltListViewWebPart instance (we need only a hidden list view created by it)
- Get XsltListViewWebPart's list view, set it as a default one
- Update XsltListViewWebPart's list view copying all property values from ListViewWebPart's view
- Deploy ListViewWebPart's, it would get the default view from the list (and the default view would have the right BaseViewID=2
- Reset default list view in the list to the previous one before web part deployments

We believe that such a flow might really work. Here is why:
- Baseviewid when using List.Views.Add in SharePoint 2013
http://stackoverflow.com/questions/19359248/baseviewid-when-using-list-views-add-in-sharepoint-2013
- ListViewWebPart & SPView – two sides of the same coin
http://stefan-stanev-sharepoint-blog.blogspot.com.au/2010/02/listviewwebpart-spview-two-sides-of.html

Again, totally understand the disappointment of not having this working well. We are closing this ticket but we'll leave the regression test looking into fixing it one we've got some time. Right now no ETA and no workaround from our side.
