### ISSUE TITLE
Upload a whole folder to a document library

### ISSUE THREAD

**Issue by flweiser** [SubPointSolutions/spmeta2#989]
Hi,
we would like to upload a whole folder to a document library.
This folder includes several subfolders and files.
Is there an easy way to do this with spmeta2, besides the obvious way of going through said folder and upload everything one-by-one?

**Comment by SubPointSupport** [comment]
Hey flweiser, We've got a helper for that - ModuleFileUtils.LoadModuleFilesFromLocalFolder(list, directoryPath). It loads the content of the folder recursively to a giving list (or folder) so that you can "attach" any folder from the file system.

Actual implementation can be found here:
https://github.com/SubPointSolutions/spmeta2/blob/a91db27843be2f800c77e1cd350be0ead7419d12/SPMeta2/SPMeta2/Syntax/Default/Utils/ModuleFileUtils.cs

Also, it has a callback Fun<string, boo> in case some files/folders needn't be included.

```cs
            var tmpDir = Path.Combine(
                                Path.GetTempPath(),
                                string.Format("m2_regression_test_CanPassTypedSyntax_Extensions_{0}", Guid.NewGuid().ToString("N")));

            Directory.CreateDirectory(tmpDir);

            var model = SPMeta2Model.NewWebModel(web =>
            {
                web.AddRandomList(list =>
                {
                    ModuleFileUtils.LoadModuleFilesFromLocalFolder(list, tmpDir);

                    list.AddRandomFolder(folder =>
                    {
                        ModuleFileUtils.LoadModuleFilesFromLocalFolder(folder, tmpDir);
                    });
                });
            });
```

**Comment by flweiser** [comment]
Great, that's exactly what we need.
Thank you!
