### ISSUE TITLE
Question regarding custom logging service

### ISSUE THREAD

**Issue by andreasblueher** [SubPointSolutions/spmeta2#997]
Hello,

I've created a custom logging service for SPMeta2 using this [tutorial](http://docs.subpointsolutions.com/spmeta2/extensibility/custom-logging.html). Everything is logged just fine, however instead of seeing some unexpected or critical message for an exception I'm currently chasing I just see: 

Ending: [ProcessModelDeployment for model:[SPMeta2.Definitions.SiteDefinition]]
Ending: [ProcessModelDeployment for model:[SPMeta2.Definitions.SiteDefinition]] 00000000-0000-0000-0000-000000000000

There are no more informations regarding an error but instead ULS log shows the following error message:
[Fehlermeldung.txt](https://github.com/SubPointSolutions/spmeta2/files/893287/Fehlermeldung.txt)

Sorry for parts of it being German, but you should get where this error is coming from.

So am I expecting too much from my custom logging service or can you point out something else I might be doing wrong?

**Comment by SubPointSupport** [comment]
Hey @andreasblueher, custom logging is all about replacing out of the box C# logger used by SPMeta2. Default implementation uses .NET trace listeners which may or may not be ideal. As per tutorial, a custom class can be written to replace out of the box one so that it would handle all the logging.

The thing is that not every single line or operation done by SPMeta2 is logged. Next, exceptions aren't handled by logging and propagated immediately within SPMeta2Exception to the caller.  

In your situation, you might consider a custom logging to connect up SPMeta2 trace to SharePoint ULS logs. Apart that, it wouldn't be much if use. Surely, redirecting SPMeta2 logs to ULS is still valuable thing for troubleshooting or auditing.

Let us know is that makes sense.

**Comment by andreasblueher** [comment]
Thanks @SubPointSupport, it's much clearer to me now and my error in reasoning was the expectation for logging to do exception handling (which doesn't make much sense thinking about it now).

I've done exactly what you suggested, all I'm missing right now is to cast the exception thrown into the logging service to SPMeta2Exception and log ModelNode and other important information (which I'm currently still missing)

`public override void Critical(int id, object message, Exception exception)
    {
        // handle critical event the way you like
       if (exception is SPMeta2Exception) {
           // read SPMeta2Exception specific properties and log them
      }
    }
`

Does this pseudo code look kind of right to you?

**Comment by SubPointSupport** [comment]
No, that's not how it works.

In your case we' suggest the following:
1) Add your own logging to ULS over provision progress:
Add simplified "Provision Progress" callback #576

2) Wrap .DeployModel() method into try-catch as this:
```cs
try {
    provisionService.Deploy(...);
} catch(Exception ex) {
   // analyse this one
   // you may have SPMeta2ModelDeploymentException and .ModelNode would have the current node on which exception occurred 
  // you may have something else, another exception here
}
```

Essentially, custom logging is needed only to redirect out of the box SPMeta2 trace into a custom location, such as ULS logs. It is not guaranteed that all exception are logged into logservice, some might be only raised immediatly without logging so that your own try-catch is needed.

**Comment by andreasblueher** [comment]
Thanks again! I added the provision progress with Verbose Traceseverity, because my custom logging is integrated into SharePoint SPDiagnosticsCategory so I can change the logged traceseverity in central administration.

I also added try/catch to my solution and it feels much more sophisticated right away 👍 

I'll close this issue as I got all the information I needed.
