### ISSUE TITLE
Object reference not set to an object instance within NoteFieldModelHandler.ProcessFieldProperties

### ISSUE THREAD

**Issue by andreasblueher** [SubPointSolutions/spmeta2#998]
Hello,

this issue is related to #997, but this is about the actual error I'm chasing.

### Brief description
For our test environment our feature using spmeta can't be activated anymore. I've narrowed it down to a single note field definition which is causing the issue.

### SharePoint API
Which version of SharePoint runtime do you use? 
* SSOM

### SPMeta2 API
Which version of SPMeta2 do you use? Use the following code snippet for your convenience. It shows all the details on SPMeta2 and SharePoint runtime used.
1.2.60 / SP2013 SP1 CU 02/2016

### SPMeta2 model
Optionally, provide SPMeta2 model in which issue occurs. That helps to identify the issue and provide the solution as far as we can.
```cs

public static NoteFieldDefinition OrderInformationDescription = new NoteFieldDefinition
            {
                Title = "Order Information",
                InternalName = "FieldOrderInformationDescription",
                Group = "FieldGroupName",
                RichText = true,
                RichTextMode = BuiltInRichTextMode.FullHtml,
                Id = new Guid("{A3CC3BD9-EEED-43E6-9F77-837EDB404785}")
            };

var ssomProvisionService = new SSOMProvisionService();

            var testModel = SPMeta2Model.NewSiteModel(site =>
                site.AddField(Definitions.Fields.OrderInformationDescription));
            ssomProvisionService.DeploySiteModel(currentSite, testModel);
```

Attached you can find the full uls log and the actual error message itself. The exception message translated is "Object reference not set to an object instance".

[ULS Log.txt](https://github.com/SubPointSolutions/spmeta2/files/893644/ULS.Log.txt)
[Fehlermeldung.txt](https://github.com/SubPointSolutions/spmeta2/files/893645/Fehlermeldung.txt)

What's really bugging me is the fact that the field exists in the site collection, it has the same internal name, it uses the same guid, it has the correct title, all the properties are set correctly, however there is this exception I can't get a hold of. Thanks for your support!

**Comment by SubPointSupport** [comment]
> For our test environment our feature using spmeta can't be activated anymore. I've narrowed it down to a single note field definition which is causing the issue.

What do you mean by "can't be activated anymore"? Did it work before? 
If you are using the same SPMeta2 version (1.2.60), then it used to work and at some point stopped?

As for the model, InternalName = "FieldOrderInformationDescription" seems to be 32 chars which is exactly the max limit for internal names. SharePoint would trim internal names up to 32 symbols. Maybe this is a root cause and it would work for something less named such as "InternalName = "FieldOrderInformation""

**Comment by andreasblueher** [comment]
> What do you mean by "can't be activated anymore"? Did it work before?

Yes the feature deploying the model was activated before for several month.

> If you are using the same SPMeta2 version (1.2.60), then it used to work and at some point stopped?

Yes we're using the same version as before.

>As for the model, InternalName = "FieldOrderInformationDescription" seems to be 32 chars which is exactly the max limit for internal names. SharePoint would trim internal names up to 32 symbols. Maybe this is a root cause and it would work for something less named such as "InternalName = "FieldOrderInformation""

Since the field has already been rolled out to prod and the field already contains several thousand elements of data, we can't change the internal name of the field. I thought about creating a new column, but this way we would have to manually transfer all information from one field to the other (which would be kind of my last resort).

**Comment by SubPointSupport** [comment]
@andreasblueher, did some investigation.

By the exception stack trace, it seem that something going on either in NoteFieldModelHandler.ProcessFieldProperties or it's base method - FieldModelHandler.ProcessFieldProperties

Here is ProcessFieldProperties of NoteFieldModelHandler:
* https://github.com/SubPointSolutions/spmeta2/blob/dev/SPMeta2/SPMeta2.SSOM/ModelHandlers/Fields/NoteFieldModelHandler.cs#L29

Has not been changed since Oct 1, 2015. In this case, a guess that:
1) casting gives null here - var typedField = field as SPFieldMultiLineText;
2) something wrong in base.ProcessFieldProperties(field, fieldModel);

So, did you guys by chance changed the actual type of the field? Is is still SPFieldMultiLineText? Would you please check?

Next, if issue is under base.ProcessFieldProperties(field, fieldModel), then the source code is here, last changed on Oct 29, 2016:
https://github.com/SubPointSolutions/spmeta2/blob/dev/SPMeta2/SPMeta2.SSOM/ModelHandlers/FieldModelHandler.cs#L403

Nearly no guesses here but let try..
1) field.Indexed = definition.Indexed; <- this one might trigger an issue on a large amount of data
2) field.JSLink = definition.JSLink; <- this one, if NULL/Empty, fails on newly created "Groups" site in O365 but we have SSOM!
3) field.Description = definition.Description ?? string.Empty; <-- updating description to Stirng.Empty fails?

Finally, SP2013 SP1 CU 02/2016 - is that Feb 2016 update for SP2013?

**Comment by andreasblueher** [comment]
Hey guys,

having the logging and exception handling plus your suggestions about possible causes for this issue I figured out what was causing the issue. Although my colleague insists he didn't change the specific field manually it appeared that list and web field where of two different kinds. One was Text and the other one was note and somewhere the a cast might have failed.

After changing both fields manually and getting them back sync with definition model the feature activation ran through. Really strange error which I don't think could have been caught perfectly by any piece of code.

Thanks (again) for the outstanding support and help (like always)

**Comment by SubPointSupport** [comment]
No worries. Glad you guys sorted it.
